config/routes.rb
Rails.application.routes.draw do
  resources :entries, except: [:edit, :update, :destroy]
  resources :workers, only: [:create]
  root to: 'entries#index'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/admin/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:nick, :email, :content)
    end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  def create
    LazyWorker.perform_async

    redirect_to(request.referer.presence || root_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.erb
<%= form_with(model: entry, local: true) do |form| %>
  <% if entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nick %>
    <%= form.text_field :nick %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Guest book</h1>

<table>
  <thead>
    <tr>
      <th>Nick</th>
      <th>Email</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.nick %></td>
        <td><%= entry.email %></td>
        <td><%= entry.content %></td>
        <td><%= link_to 'Show', entry %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entry', new_entry_path %>

<%= link_to 'Start a job', workers_path, method: :post %>

app/views/entries/new.html.erb
<h1>New Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nick:</strong>
  <%= @entry.nick %>
</p>

<p>
  <strong>Email:</strong>
  <%= @entry.email %>
</p>

<p>
  <strong>Content:</strong>
  <%= @entry.content %>
</p>

<%= link_to 'Back', entries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsExampleApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>

    <div id="js-test"></div>
    <%= image_tag 'image_test.png' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>